# Generated by Django 2.0 on 2018-11-23 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField(blank=True, default=0, max_length=100)),
                ('lat', models.FloatField(blank=True, default=0, max_length=100)),
                ('speed', models.FloatField(blank=True, default=0, max_length=100)),
                ('accuracy', models.FloatField(blank=True, default=0, max_length=100)),
                ('address', models.TextField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Farmland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.TextField(default=0)),
                ('address', models.TextField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Herdsman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('phone', models.IntegerField(default='00000000')),
                ('userid', models.IntegerField(default=0)),
                ('lng', models.FloatField(blank=True, default=0, max_length=100)),
                ('lat', models.FloatField(blank=True, default=0, max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('address', models.TextField(default=0)),
                ('last_post', models.DateField(auto_now_add=True)),
                ('is_trespassing', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField(blank=True, default=0, max_length=100)),
                ('lat', models.FloatField(blank=True, default=0, max_length=100)),
                ('speed', models.FloatField(blank=True, default=0, max_length=100)),
                ('accuracy', models.FloatField(blank=True, default=0, max_length=100)),
                ('address', models.TextField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('herdsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Herdsman')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='bounds',
            name='farmland',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Farmland'),
        ),
    ]
