# Generated by Django 2.0 on 2018-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmland',
            name='phone',
            field=models.IntegerField(default='00000000'),
        ),
    ]
