# Generated by Django 2.0 on 2018-11-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_farmland_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bounds',
            new_name='Bound',
        ),
    ]
