# Generated by Django 2.0 on 2018-12-02 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181202_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 2, 14, 42, 6, 698608))),
                ('stop', models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 2, 14, 42, 6, 699608))),
                ('herdsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Herdsman')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 2, 14, 42, 6, 700609)),
        ),
        migrations.AddField(
            model_name='location',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Collection'),
        ),
    ]
