# Generated by Django 2.0 on 2018-12-08 06:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20181202_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bound',
            new_name='Bounds',
        ),
        migrations.RenameField(
            model_name='farmland',
            old_name='owner_name',
            new_name='community',
        ),
        migrations.AddField(
            model_name='farmland',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmland', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 8, 7, 35, 14, 417220)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 8, 7, 35, 14, 417220)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 8, 7, 35, 14, 419218)),
        ),
    ]
