# Generated by Django 2.0 on 2018-12-10 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20181210_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmland',
            name='address',
        ),
        migrations.AddField(
            model_name='farmland',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 10, 14, 57, 0, 493885)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 10, 14, 57, 0, 493885)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 10, 14, 57, 0, 495883)),
        ),
    ]
