# Generated by Django 2.0 on 2018-12-11 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20181211_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='herdsman',
            name='no_of_cattle',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 11, 20, 30, 44, 856851)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 11, 20, 30, 44, 856851)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 11, 20, 30, 44, 857850)),
        ),
    ]
