# Generated by Django 2.0 on 2018-12-13 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20181211_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='lat',
            field=models.FloatField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='lng',
            field=models.FloatField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 11, 26, 59, 75640)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 11, 26, 59, 75640)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 11, 26, 59, 77643)),
        ),
    ]
