# Generated by Django 2.0 on 2018-12-13 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20181213_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmland',
            name='details',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='farmland',
            name='is_panicking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herdsman',
            name='details',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='herdsman',
            name='is_panicking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 14, 8, 54, 225217)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 14, 8, 54, 225217)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 14, 8, 54, 226216)),
        ),
    ]
