# Generated by Django 2.0 on 2018-12-13 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20181213_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bounds',
            options={'ordering': ('date',), 'verbose_name_plural': 'Bounds'},
        ),
        migrations.AlterModelOptions(
            name='herdsman',
            options={'ordering': ('slug',), 'verbose_name_plural': 'Herdsmen'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 20, 17, 4, 252567)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 20, 17, 4, 252567)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 13, 20, 17, 4, 254064)),
        ),
    ]
