# Generated by Django 2.0 on 2018-12-16 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20181214_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='treated',
            new_name='is_resolved',
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 16, 11, 28, 11, 747553)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 16, 11, 28, 11, 747553)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 16, 11, 28, 11, 748553)),
        ),
    ]
