# Generated by Django 2.0 on 2018-12-16 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20181216_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmland',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 16, 23, 11, 43, 623948)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 16, 23, 11, 43, 623948)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 16, 23, 11, 43, 625946)),
        ),
    ]
