# Generated by Django 2.0 on 2019-01-08 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20190107_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='herdsman',
            name='token',
            field=models.CharField(blank=True, default='xxoopz', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 8, 20, 42, 50, 48884)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 8, 20, 42, 50, 48884)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 8, 20, 42, 50, 50884)),
        ),
    ]
