# Generated by Django 2.0 on 2019-02-13 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20190109_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmland',
            name='products',
            field=models.TextField(default='Not Set'),
        ),
        migrations.AddField(
            model_name='farmland',
            name='static_state',
            field=models.TextField(default='Not Set'),
        ),
        migrations.AddField(
            model_name='herdsman',
            name='static_state',
            field=models.TextField(default='Not Set'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 13, 18, 27, 38, 694153)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 13, 18, 27, 38, 694153)),
        ),
        migrations.AlterField(
            model_name='farmland',
            name='community',
            field=models.TextField(default='Not Set'),
        ),
        migrations.AlterField(
            model_name='herdsman',
            name='address',
            field=models.TextField(default='Not Set'),
        ),
        migrations.AlterField(
            model_name='herdsman',
            name='state',
            field=models.TextField(default='Not Set'),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 13, 18, 27, 38, 697166)),
        ),
    ]
