# Generated by Django 2.0 on 2019-02-13 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20190213_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmland',
            name='state',
            field=models.TextField(default='Not Set'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 13, 23, 58, 21, 756151)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 13, 23, 58, 21, 756151)),
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 13, 23, 58, 21, 756151)),
        ),
    ]
