# Generated by Django 2.0 on 2018-10-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='months',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
