# Generated by Django 2.0 on 2018-10-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_months_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='date',
            field=models.DateField(blank=True, default='2018-03-15', max_length=40, null=True),
        ),
    ]
