# Generated by Django 2.0 on 2018-10-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_auto_20181021_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(blank=True, default='2018-03-15', max_length=40, null=True),
        ),
    ]
