# Generated by Django 2.0 on 2018-11-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0004_auto_20181025_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='has_special_fee',
            field=models.BooleanField(default=False),
        ),
    ]
