# Generated by Django 2.0 on 2018-11-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_auto_20181130_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='has_special_fee',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='stays_in',
        ),
    ]
