# Generated by Django 2.0 on 2019-01-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0014_auto_20190108_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='if_farmer',
        ),
        migrations.RemoveField(
            model_name='session',
            name='if_herdsman',
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmland', to='main.Farmland'),
        ),
    ]
