# Generated by Django 2.0 on 2018-09-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180418_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField(blank=True, default=0, max_length=100)),
                ('lat', models.FloatField(blank=True, default=0, max_length=100)),
                ('address', models.TextField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
