# Generated by Django 2.0 on 2018-10-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180929_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('slug',)},
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default='0803312244', max_length=40),
        ),
        migrations.AddField(
            model_name='location',
            name='accuracy',
            field=models.FloatField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='speed',
            field=models.FloatField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=40),
        ),
    ]
